add unix readline's keymap in INSERT_MODE
siduck76/NvChad pull request #238
Opened 2021-08-13 16:14 UTC by curtainp

when I'm coding, sometime won't exit insert mode, so this unix `readline` like keymap useful.

2021-08-13 16:26 UTC, JustSage commented
Personally I think this is a really bad habit and I advise against integrating this with insert mode. 
However, this could be useful in command mode.

2021-08-14 03:09 UTC, siduck76 commented
@curtainp could you add two mappings for moving the cursor <up><down>?

2021-08-14 03:12 UTC, siduck76 commented
> Personally I think this is a really bad habit and I advise against integrating this with insert mode.
> However, this could be useful in command mode.

might be very helpful for many so I'll add an option to enable /disable this.

2021-08-14 05:25 UTC, G-Rowell requested changes
Add enable option, assume disable if option is false or does not exist

2021-08-14 05:25 UTC, G-Rowell commented on lua/mappings.lua
> +-- unix readline's keymap
Maybe wrap this in a lua function and check if:
- if the `chadrc.lua` var does not exist, assume this functionality should be disabled (return, early exit the function)
- if the `chadrc.lua` var exists and is true, then run this block

2021-08-14 05:25 UTC, G-Rowell commented on lua/chadrc.lua
> +        unix_keymap = {
Function mentioned in my comment below should check the table in `line 9 (above)`, `options`

2021-08-14 05:25 UTC, G-Rowell commented
@curtainp 
Lemme know if you want some help or anything!

2021-08-14 05:37 UTC, G-Rowell requested changes
This commit should be removed from your branch,

Run `git rebase --interactive HEAD~3`

change `pick` to the delete option for this commit/merge

Then instead of doing the merge to update your branch,
do `git pull --rebase upstream main` (assuming you set siduck76/NvChad as upstream)

This way you avoid adding a merge commit just to update your local branch!

Hope this helps! 

(note, because you are modifying the history of your branch, you'll have to update the online/remote copy with `git push origin --force` once your done)

2021-08-14 05:39 UTC, G-Rowell commented
Let me know if you have any questions at all,
happy to help!

2021-08-14 06:07 UTC, curtainp commented
@G-Rowell thanks, I have daily somethings bother, the fix I have finished, now to push

2021-08-14 06:08 UTC, G-Rowell commented
> @G-Rowell thanks, I have daily things bother, the fix I have finished, now to push 

No problem,
We all have other things we need to do.

@ me when you have pushed your changes or have a question

2021-08-14 06:22 UTC, G-Rowell commented
Reading now

2021-08-14 06:24 UTC, curtainp commented
> Reading now

there seems somethings wrong, i checkout a new branch to do this, wait me @G-Rowell

2021-08-14 06:28 UTC, closed without merging

2021-08-14 06:31 UTC, G-Rowell commented
@curtainp 

Yeah, think you've got some git config issues
Happy to walk you through how setup a PR nicely